// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

type GameId = string | number;

type GameConfig = {
    name: string;
    url: string;
    id?: GameId;
    cssId?: string;
}

type AppConfig = {
    games: GameConfig[];
    background: string;
    backgrounds?: string[];
    backgroundColor: string;
    textColor: string;
    accentColor: string;
    cachePath?: string;
    autoCacheClear?: boolean;
    customCSS?: string;
}


type UserData = {
    cachePath?: string;
    [index: GameId]: GameUserData;
}

type GameUserData = {
    password?: number[];
    user: string;
    adminPassword?: number[];
}
type GameUserDataDecrypted = {
    password?: string;
    user: string;
    adminPassword?: string;
}

type SaveUserData = { gameId: GameId; password: string; user: string; adminPassword: string };

type WindowData = {
    gameId: GameId;
    autoLogin: boolean;
}

type WindowsData = {
    [index: number]: WindowData;
}