// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;
declare const api: typeof import("./api").default;

type GameConfig = {
    name: string;
    url: string;
    id?: number;
}

type AppConfig = {
    games: GameConfig[];
    background: string;
    backgroundColor: string;
    textColor: string;
    accentColor: string;
}


type UserData = {
    [index: string]: GameUserData
}

type GameUserData = {
    password?: number[];
    user: string;
    adminPassword?: number[];
}
type GameUserDataDecrypted = {
    password?: string;
    user: string;
    adminPassword?: string;
}